### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by johnny-yu** [enhuiz/vall-e#101]
`python -m vall_e.train  yaml=data/test/ar.yml ` on macOS   m1

[PosixPath('data/test/test.qnt.pt'), PosixPath('data/test/test2.qnt.pt')] 路径0
{'test': [PosixPath('data/test/test.qnt.pt'), PosixPath('data/test/test2.qnt.pt')]} 路径1
[PosixPath('data/test/test.qnt.pt'), PosixPath('data/test/test2.qnt.pt')] 路径2
[] 路径0
{'test': [PosixPath('data/test/test.qnt.pt'), PosixPath('data/test/test2.qnt.pt')]} 路径1
[] 路径2
2023-05-31 20:24:26 - vall_e.data - INFO - GR=0;LR=0 - 
{'</s>': 1, '<s>': 2, 'AH0': 3, 'D': 4, 'ER1': 5, 'HH': 6, 'L': 7, 'OW1': 8, 'W': 9, '_': 10}
2023-05-31 20:24:26 - vall_e.data - INFO - GR=0;LR=0 - 
{'test': 0}
2023-05-31 20:24:26 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (train): 2.
2023-05-31 20:24:26 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (val): 0.
[2023-05-31 20:24:26,592] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/Users/johnny/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/johnny/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/vall_e/train.py", line 128, in <module>
    main()
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/vall_e/train.py", line 119, in main
    trainer.train(
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/vall_e/utils/trainer.py", line 125, in train
    engines = engines_loader()
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/vall_e/utils/engines.py", line 22, in __init__
    super().__init__(None, *args, **kwargs)
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 257, in __init__
    dist.init_distributed(dist_backend=self.dist_backend,
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 656, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 36, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 40, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
  File "/Users/johnny/miniconda3/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

**Comment by kdrkdrkdr** [comment]
change nccl to gloo
