### ISSUE TITLE
Missing `test_data_dirs`

### ISSUE THREAD

**Issue by arstropica** [enhuiz/vall-e#13]
The last commit: [2e9f503](https://github.com/enhuiz/vall-e/commit/2e9f5030a3633837c0b8e9688ca288968b5e182f) enforces the presence of an existing `paths` argument for the `VALLEDatset` class constructor. 
However, I think that the constructor throws the following error at the start of training due to a missing path variable from `cfg.test_data_dirs`.

`Traceback (most recent call last):
  File "/home/xxxxxx/miniconda3/envs/valle/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxxxxx/miniconda3/envs/valle/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxxxxx/dev/repos/vall-e/vall_e/train.py", line 130, in <module>
    main()
  File "/home/xxxxxx/dev/repos/vall-e/vall_e/train.py", line 33, in main
    train_dl, train_for_val_dl, val_dl, test_dl = create_train_val_dataloader()
  File "/home/xxxxxx/dev/repos/vall-e/vall_e/data.py", line 285, in create_train_val_dataloader
    train_dataset, val_dataset, test_dataset = create_datasets()
  File "/home/xxxxxx/dev/repos/vall-e/vall_e/data.py", line 274, in create_datasets
    test_dataset = VALLEDatset(
  File "/home/xxxxxx/dev/repos/vall-e/vall_e/data.py", line 111, in __init__
    raise ValueError("No valid path is found. ")
ValueError: No valid path is found. `

What does the `test_data_dirs` represent in the config class?  
Is this another argument we should be passing in the cli?

**Comment by vollkorncrafter** [comment]
I have the excact same problem lol

**Comment by vollkorncrafter** [comment]
do you know if it works with a version of the library before [2e9f503](https://github.com/enhuiz/vall-e/commit/2e9f5030a3633837c0b8e9688ca288968b5e182f) ?

**Comment by vollkorncrafter** [comment]
I forked this repo and removed the new code, everything is working now

**Comment by enhuiz** [comment]
Fixed https://github.com/enhuiz/vall-e/commit/d80ef1d97071b21d1a6cfe95322c3112697a99d4

**Comment by arstropica** [comment]
In [train.py](https://github.com/enhuiz/vall-e/blob/d80ef1d97071b21d1a6cfe95322c3112697a99d4/vall_e/train.py#L119), the test dataset is being evaluated with the input data. So I am thinking that there is a reason it's there.  Just not clear on why.

```
    def eval_fn(engines):
        run_eval(engines, "train_for_val", train_for_val_dl)
        run_eval(engines, "val", val_dl)
        run_eval(engines, "test", test_dl)
```

**Comment by arstropica** [comment]
> Fixed [d80ef1d](https://github.com/enhuiz/vall-e/commit/d80ef1d97071b21d1a6cfe95322c3112697a99d4)

Ha! Ok, thanks for the quick response!

**Comment by vollkorncrafter** [comment]
Thank you 🙏
