### ISSUE TITLE
I get this error on colab

### ISSUE THREAD

**Issue by allthingssecurity** [enhuiz/vall-e#16]
!python -m vall_e 'hello world this is getting interesting' data/test/test.wav toy.wav
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/__main__.py", line 43, in <module>
    main()
  File "/content/vall-e/vall_e/__main__.py", line 29, in main
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
  File "/content/vall-e/vall_e/__main__.py", line 29, in <listcomp>
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
KeyError: 'DH'

**Comment by enhuiz** [comment]
The training set does not contain the phoneme DH. The current colab is a demo for training and does not contain a usable model.
