### ISSUE TITLE
How to use the absolute path of the data for training

### ISSUE THREAD

**Issue by smile-struggler** [enhuiz/vall-e#23]
I want to use the absolute path of my data for training, but when I do this, the following error will occur, how to solve it?

```
0%|                                                                                                                                  | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "XXX/anaconda3/envs/valle/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "XXX/anaconda3/envs/valle/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "XXX/project/2023/230118-valle/vall_e/train.py", line 128, in <module>
    main()
  File "XXX/project/2023/230118-valle/vall_e/train.py", line 119, in main
    trainer.train(
  File "XXX/project/2023/230118-valle/vall_e/utils/trainer.py", line 205, in train
    eval_fn(engines=engines)
  File "XXX/project/2023/230118-valle/vall_e/utils/distributed.py", line 69, in wrapped
    return fn(*args, **kwargs)
  File "XXX/project/2023/230118-valle/vall_e/train.py", line 116, in eval_fn
    run_eval(engines, "subtrain", subtrain_dl)
  File "XXX/anaconda3/envs/valle/lib/python3.10/site-packages/torch-1.13.1-py3.10-linux-x86_64.egg/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "XXX/project/2023/230118-valle/vall_e/train.py", line 97, in run_eval
    relpath = path.relative_to(cfg.data_root)
  File "XXX/anaconda3/envs/valle/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/data/public/libriTTS/LibriTTS/train-clean-100/103/1241/103_1241_000000_000001.qnt.pt' is not in the subpath of 'data' OR one path is relative and the other is absolute.
```

**Comment by enhuiz** [comment]
Try to add 

```yaml
data_root: /data/public/libriTTS/
```

In your configuration.

**Comment by smile-struggler** [comment]
> Try to add
> 
> ```yaml
> data_root: /data/public/libriTTS/
> ```
> 
> In your configuration.

Thanks for your reply! Now I changed the configuration to this:
```
data_root: /data/public/libriTTS/
data_dirs: [/data/public/libriTTS/LibriTTS]
```
And it seems to run well, is it correct to write this way, both of them use absolute addresses?
