### ISSUE TITLE
Doesn't generate any sentences other than hello world 

### ISSUE THREAD

**Issue by hiltercoty** [enhuiz/vall-e#26]
Hi,

I've followed all the steps in the Colab notebook. In the end, I wanted to generate my own sentence, like this:

```
!python -m vall_e 'why this is not working' data/test/test.wav toy.wav
```

But it always returns errors like this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/__main__.py", line 43, in <module>
    main()
  File "/content/vall-e/vall_e/__main__.py", line 29, in main
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
  File "/content/vall-e/vall_e/__main__.py", line 29, in <listcomp>
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
KeyError: 'AY1'
```

What could be wrong?

**Comment by christopherwoodall** [comment]
The model doesn't know any other phenom pairs. With the default audio, you can try things like "world hello" or "hello hero".

**Comment by JaejinCho** [comment]
https://github.com/enhuiz/vall-e/issues/22
