### ISSUE TITLE
Getting "No valid path is found for training". Using WSL + followed the Collab

### ISSUE THREAD

**Issue by ghost** [enhuiz/vall-e#27]
python3 -m vall_e.train yaml=config/test/ar.yml
1it [00:00, 207.85it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/varunmayya/.local/lib/python3.10/site-packages/vall_e/train.py", line 128, in <module>
    main()
  File "/home/varunmayya/.local/lib/python3.10/site-packages/vall_e/train.py", line 33, in main
    train_dl, subtrain_dl, val_dl = create_train_val_dataloader()
  File "/home/varunmayya/.local/lib/python3.10/site-packages/vall_e/data.py", line 266, in create_train_val_dataloader
    train_dataset, val_dataset = create_datasets()
  File "/home/varunmayya/.local/lib/python3.10/site-packages/vall_e/data.py", line 247, in create_datasets
    train_dataset = VALLEDatset(
  File "/home/varunmayya/.local/lib/python3.10/site-packages/vall_e/data.py", line 105, in __init__
    raise ValueError("No valid path is found for training.")
ValueError: No valid path is found for training.

**Comment by OrjwanZaafarani** [comment]
Hi @varunmayya
1. Use `cd` to navigate to the project folder `/vall-e`
2. Check the `data_dirs` key in the config file `config/test/ar.yml`. Does it point to the same folder of your dataset?

**Comment by ghost** [comment]
Still doesn't work.
This is my folder structure:

vall-e 
  config > test
  data > test
  logs
  
  MY AR file's first line is: data_dirs: [data/test]

**Comment by finardi** [comment]
Did you change the audios in test foder? You need to have a pair to train/valid sets.

**Comment by ghost** [comment]
No I didn't, it's the default

**Comment by ghost** [comment]
here's my setup, still doens't work

![image](https://user-images.githubusercontent.com/3878337/214547477-2a90f9ca-5477-4f39-ae6e-9454f105d22a.png)

![image](https://user-images.githubusercontent.com/3878337/214547563-d5ea0367-dc28-4c77-b1c9-7de47a995381.png)

![image](https://user-images.githubusercontent.com/3878337/214547602-521d1778-004b-4d18-91f2-4fea328e7d54.png)

![image](https://user-images.githubusercontent.com/3878337/214547653-769704bd-c637-489b-b625-46bedcb11c84.png)

**Comment by ghost** [comment]
The command I'm using: python3 -m vall_e.train yaml=config/second/ar.yml

**Comment by OrjwanZaafarani** [comment]
[data/test] should be [data/second]
