### ISSUE TITLE
Training with my own audios, does it works?

### ISSUE THREAD

**Issue by bgondell** [enhuiz/vall-e#29]
### Discussed in https://github.com/enhuiz/vall-e/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **bgondell** January 24, 2023</sup>
I cloned the collab and uploaded a pair of audios with my voice, but when tried to generate a "hello world", did not work.

Not sure if it's a very specific demo, or can be trained for more examples.

Thanks!!

Command:
`!python -m vall_e 'hello world' data/bruno/file_391.wav toy.wav`

Output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/__main__.py", line 43, in <module>
    main()
  File "/content/vall-e/vall_e/__main__.py", line 29, in main
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
  File "/content/vall-e/vall_e/__main__.py", line 29, in <listcomp>
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
KeyError: 'HH'
```
</div>

**Comment by d-warfield** [comment]
Did you add the at train and test files in  the `bruno` directory?

For example:

`bruno2.phn.txt`
`bruno2.qnt.pt`

You'll have also to make sure that you change the `[directory/test]`  that's in you `/config/test` file to `[directory/bruno]`

This should get it running!

**Comment by bgondell** [comment]
Yes, I run again all the step on a Colab, still got same error. 
Probably is a very stupid error by me.


Hope you can see the outputs.
https://colab.research.google.com/drive/1MSljpiqUnWJJ19R3Foo5KVpVsTh-wMQn?usp=sharing

**Comment by souvikg544** [comment]
Hello ! could you find anything on this regard
