### ISSUE TITLE
There is an error when installing Deepspeed.

### ISSUE THREAD

**Issue by lss9566** [enhuiz/vall-e#3]
I am a person who is studying coding. I'm not good enough, but I'm trying. Thank you for posting good data, and other programs are installed well, but only Deepspeed has an error. My operating system is Windows 10, and my graphics card is built-in. I went to the Deepspeed homepage and tried all sorts of methods, but it didn't work. Please help me. I even searched it, but I have no idea.

anaconda powershell

(base) PS C:\python\vall-e> pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.7.7.tar.gz (712 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-kejson7y\deepspeed_22029de4adec4e19bdd6eb3d6bf7b01a\setup.py", line 164, in <module>
          ext_modules.append(builder.builder())
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-kejson7y\deepspeed_22029de4adec4e19bdd6eb3d6bf7b01a\op_builder\builder.py", line 599, in builder
          assert_no_cuda_mismatch()
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-kejson7y\deepspeed_22029de4adec4e19bdd6eb3d6bf7b01a\op_builder\builder.py", line 89, in assert_no_cuda_mismatch
          cuda_major, cuda_minor = installed_cuda_version()
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-kejson7y\deepspeed_22029de4adec4e19bdd6eb3d6bf7b01a\op_builder\builder.py", line 41, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)  
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(base) PS C:\python\vall-e> 

git bash

user@DESKTOP-NF5O47M MINGW64 /c/python
$ DS_BUILD_OPS=1 pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.7.7.tar.gz (712 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.      
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-5thu072j\deepspeed_1ff8ac6fbc8a4942a69e6ab2cf187056\setup.py", line 164, in <module>
          ext_modules.append(builder.builder())
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-5thu072j\deepspeed_1ff8ac6fbc8a4942a69e6ab2cf187056\op_builder\builder.py", line 599, in builder
          assert_no_cuda_mismatch()
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-5thu072j\deepspeed_1ff8ac6fbc8a4942a69e6ab2cf187056\op_builder\builder.py", line 89, in assert_no_cuda_mismatch 
          cuda_major, cuda_minor = installed_cuda_version()
        File "C:\Users\Public\Documents\ESTsoft\CreatorTemp\pip-install-5thu072j\deepspeed_1ff8ac6fbc8a4942a69e6ab2cf187056\op_builder\builder.py", line 41, in installed_cuda_version  
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

user@DESKTOP-NF5O47M MINGW64 /c/python
$

**Comment by SkyYap** [comment]
Having the same issue when I tried `pip install git+https://github.com/enhuiz/vall-e`

**Comment by lss9566** [comment]
It's the same for me.

**Comment by enhuiz** [comment]
Take a look here: https://github.com/microsoft/DeepSpeed#requirements

**Comment by SkyYap** [comment]
Tried 
`C:\Users\sk_16\Documents\GitHub\vall-e> pip install torch`
Requirement already satisfied: torch in c:\users\sk_16\appdata\local\programs\python\python310\lib\site-packages (1.13.1)
Requirement already satisfied: typing-extensions in c:\users\sk_16\appdata\local\programs\python\python310\lib\site-packages (from torch) (4.4.
0)

Then I try `pip install deepspeed`

The error shows this:
```
Collecting deepspeed
  Using cached deepspeed-0.7.7.tar.gz (712 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sk_16\AppData\Local\Temp\pip-install-9r4bidrd\deepspeed_c4869c724bb1444da36e64ed29606806\setup.py", line 164, in <module
>
          ext_modules.append(builder.builder())
        File "C:\Users\sk_16\AppData\Local\Temp\pip-install-9r4bidrd\deepspeed_c4869c724bb1444da36e64ed29606806\op_builder\builder.py", line 59
9, in builder
          assert_no_cuda_mismatch()
        File "C:\Users\sk_16\AppData\Local\Temp\pip-install-9r4bidrd\deepspeed_c4869c724bb1444da36e64ed29606806\op_builder\builder.py", line 89
, in assert_no_cuda_mismatch
          cuda_major, cuda_minor = installed_cuda_version()
        File "C:\Users\sk_16\AppData\Local\Temp\pip-install-9r4bidrd\deepspeed_c4869c724bb1444da36e64ed29606806\op_builder\builder.py", line 41
, in installed_cuda_version
          assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
      AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capa
bility for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by enhuiz** [comment]
The error says you either don't have the CUDA toolkit installed or have not properly set the CUDA_HOME.

```
CUDA_HOME does not exist, unable to compile CUDA op(s)
```

Check the instruction related to this from the link I provided above:

> A CUDA or ROCm compiler such as [nvcc](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#introduction) or [hipcc](https://github.com/ROCm-Developer-Tools/HIPCC) used to compile C++/CUDA/HIP extensions.

**Comment by SkyYap** [comment]
> The error says you either don't have the CUDA toolkit installed or have not properly set the CUDA_HOME.
> 
> ```
> CUDA_HOME does not exist, unable to compile CUDA op(s)
> ```
> 
> Check the instruction related to this from the link I provided above:
> 
> > A CUDA or ROCm compiler such as [nvcc](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#introduction) or [hipcc](https://github.com/ROCm-Developer-Tools/HIPCC) used to compile C++/CUDA/HIP extensions.

Thanks! It worked perfectly!

**Comment by enhuiz** [comment]
Closing this as the requirements for DeepSpeed have been added to the README.
