### ISSUE TITLE
Any advice on solving multi-GPU training failure?

### ISSUE THREAD

**Issue by XuanGhahahaha** [enhuiz/vall-e#51]
Hi, thanks for your kindly sharing your code!!!

I have tried to use Librispeech dataset for training, and according to other issues, I run:
`CUDA_VISIBLE_DEVICES=1,2,3,4,5 python -m torch.distributed.launch --nproc_per_node 5 -m vall_e.train yaml=config/LibriSpeech/ar.yml`

But firstly the code stuck for minutes, with information:
```
2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=0;LR=0 - 
New epoch starts.
2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=3;LR=3 - 
New epoch starts.
2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=4;LR=4 - 
New epoch starts.
2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=2;LR=2 - 
New epoch starts.
2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=1;LR=1 - 
New epoch starts.
```
Then the training failed, with errors as follows:
```
[E ProcessGroupNCCL.cpp:821] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801567 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801540 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801537 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801594 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801537 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801540 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801594 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801567 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2038811 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 2038810) of binary: /data3/gx/anaconda3/envs/vall-e/bin/python
Traceback (most recent call last):
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
vall_e.train FAILED
--------------------------------------------------------
Failures:
[1]:
  time      : 2023-02-19_15:14:41
  host      : amax
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 2038812)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2038812
[2]:
  time      : 2023-02-19_15:14:41
  host      : amax
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 2038813)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2038813
[3]:
  time      : 2023-02-19_15:14:41
  host      : amax
  rank      : 4 (local_rank: 4)
  exitcode  : -6 (pid: 2038814)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2038814
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-19_15:14:41
  host      : amax
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 2038810)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2038810
========================================================
```

I run this code in five RTX 3090 cards. Could you please tell me how to handle these errors? Or could you give some advice on what reason may cause these errors? Thank you!

**Comment by XuanGhahahaha** [comment]
By the way, I am curious on why choosing deepspeed to implement this paper, but not ddp in pytorch. Thank you!

**Comment by ghost** [comment]
reduce the batch size can help

**Comment by NiHaoUCAS** [comment]
> Hi, thanks for your kindly sharing your code!!!
> 
> I have tried to use Librispeech dataset for training, and according to other issues, I run: `CUDA_VISIBLE_DEVICES=1,2,3,4,5 python -m torch.distributed.launch --nproc_per_node 5 -m vall_e.train yaml=config/LibriSpeech/ar.yml`
> 
> But firstly the code stuck for minutes, with information:
> 
> ```
> 2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=0;LR=0 - 
> New epoch starts.
> 2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=3;LR=3 - 
> New epoch starts.
> 2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=4;LR=4 - 
> New epoch starts.
> 2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=2;LR=2 - 
> New epoch starts.
> 2023-02-19 14:44:33 - vall_e.utils.trainer - INFO - GR=1;LR=1 - 
> New epoch starts.
> ```
> 
> Then the training failed, with errors as follows:
> 
> ```
> [E ProcessGroupNCCL.cpp:821] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801567 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:821] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801540 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801537 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801594 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801537 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801540 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801594 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=139, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801567 milliseconds before timing out.
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2038811 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 2038810) of binary: /data3/gx/anaconda3/envs/vall-e/bin/python
> Traceback (most recent call last):
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 195, in <module>
>     main()
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 191, in main
>     launch(args)
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launch.py", line 176, in launch
>     run(args)
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
>     elastic_launch(
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/data3/gx/anaconda3/envs/vall-e/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ========================================================
> vall_e.train FAILED
> --------------------------------------------------------
> Failures:
> [1]:
>   time      : 2023-02-19_15:14:41
>   host      : amax
>   rank      : 2 (local_rank: 2)
>   exitcode  : -6 (pid: 2038812)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 2038812
> [2]:
>   time      : 2023-02-19_15:14:41
>   host      : amax
>   rank      : 3 (local_rank: 3)
>   exitcode  : -6 (pid: 2038813)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 2038813
> [3]:
>   time      : 2023-02-19_15:14:41
>   host      : amax
>   rank      : 4 (local_rank: 4)
>   exitcode  : -6 (pid: 2038814)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 2038814
> --------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-02-19_15:14:41
>   host      : amax
>   rank      : 0 (local_rank: 0)
>   exitcode  : -6 (pid: 2038810)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 2038810
> ========================================================
> ```
> 
> I run this code in five RTX 3090 cards. Could you please tell me how to handle these errors? Or could you give some advice on what reason may cause these errors? Thank you!

I meet the same problem, do you solve it?
