### ISSUE TITLE
can't quantize data

### ISSUE THREAD

**Issue by yuanbit** [enhuiz/vall-e#55]
When I tried to quantize the data and enter the command

`python -m vall_e.emb.qnt data/your_data`

I got this error:

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/vall-e/vall_e/emb/qnt.py", line 3, in <module>
    from functools import cache
ImportError: cannot import name 'cache' from 'functools' (/usr/lib/python3.8/functools.py)
`

**Comment by eonglints** [comment]
You need to be on Python 3.10.7, `pyenv` is your friend.

**Comment by cantabile-kwok** [comment]
`cache` is only introduced in functools from python 3.10, so it must be used.
