### ISSUE TITLE
Error on Custom Samples Training

### ISSUE THREAD

**Issue by NaeemKhanNiazi** [enhuiz/vall-e#68]
Hi @enhuiz,

Thank you very helpful work . I am using this code to train my own dataset sample on the given code. I am using the following Colab Notebook

(Vall-e Note Book)[https://colab.research.google.com/drive/1wEze0kQ0gt9B3bQmmbtbSXCoCTpq5vg-?usp=sharing]

I created a wav file and txt file which contain audio and corresponding text

- test.wav
- test.normalized.txt

After preprocessing , I get two files

- test.phn.txt
- test.qnt.pt

But while I try to run the command

```

!python -m vall_e.train yaml=config/test/ar.yml

```

But I am facing following error 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Colab Notebooks/VALL_E/vall-e/vall_e/train.py", line 129, in <module>
    main()
  File "/content/drive/MyDrive/Colab Notebooks/VALL_E/vall-e/vall_e/train.py", line 34, in main
    train_dl, subtrain_dl, val_dl = create_train_val_dataloader()
  File "/content/drive/MyDrive/Colab Notebooks/VALL_E/vall-e/vall_e/data.py", line 268, in create_train_val_dataloader
    train_dataset, val_dataset = create_datasets()
  File "/content/drive/MyDrive/Colab Notebooks/VALL_E/vall-e/vall_e/data.py", line 249, in create_datasets
    train_dataset = VALLEDatset(
  File "/content/drive/MyDrive/Colab Notebooks/VALL_E/vall-e/vall_e/data.py", line 105, in __init__
    raise ValueError("No valid path is found for training.")
ValueError: No valid path is found for training.
```

**Comment by lyk7539511** [comment]
same problem, you solved that?

**Comment by Spydernaz** [comment]
Same problem here, any updates?

**Comment by Spydernaz** [comment]
Not sure if this helps anyone else, I was able to get around by using max_phones in the config, see below... Not sure what it should be set to, but this seemed to work for me, hope it helps someone 👍🏼 
```
data_dirs: [data/spydernaz]

model: ar-quarter
batch_size: 1
eval_batch_size: 1
save_ckpt_every: 500
eval_every: 500
max_iter: 1000

max_phones: 5000
```
