### ISSUE TITLE
 Failed to find any .qnt.pt file in [PosixPath('data/put')]

### ISSUE THREAD

**Issue by ws-mkulas** [enhuiz/vall-e#7]
```bash

mkulas@debian:~/valle/data$ find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
.
 |-put
 | |-put.txt
 | |-ar.yml
 | |-put.wav
 | |-nar.yml
 |-.normalized.txt
 |-put.txt
 |-test
 | |-ar.yml
 | |-nar.yml
 |-put.wav
 |-audio.wav
 |-LibriTTS
 | |-nar-quarter.yml
 | |-ar.yml
 | |-nar.yml
 | |-ar-quarter.yml
```

```bash
$ python -m vall_e.emb.qnt data/put/put.wav
0it [00:00, ?it/s]

$ python -m vall_e.emb.g2p data/put/put.txt
0it [00:00, ?it/s]

$ python -m vall_e.train yaml=data/put/ar.yml

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mkulas/valle/lib/python3.10/site-packages/vall_e/train.py", line 130, in <module>
    main()
  File "/home/mkulas/valle/lib/python3.10/site-packages/vall_e/train.py", line 33, in main
    train_dl, train_for_val_dl, val_dl, test_dl = create_train_val_dataloader()
  File "/home/mkulas/valle/lib/python3.10/site-packages/vall_e/data.py", line 280, in create_train_val_dataloader
    train_dataset, val_dataset, test_dataset = create_datasets()
  File "/home/mkulas/valle/lib/python3.10/site-packages/diskcache/core.py", line 1877, in wrapper
    result = func(*args, **kwargs)
  File "/home/mkulas/valle/lib/python3.10/site-packages/vall_e/data.py", line 254, in create_datasets
    train_paths, val_paths = _load_train_val_paths()
  File "/home/mkulas/valle/lib/python3.10/site-packages/vall_e/data.py", line 226, in _load_train_val_paths
    raise RuntimeError(f"Failed to find any .qnt.pt file in {cfg.data_dirs}.")
RuntimeError: Failed to find any .qnt.pt file in [PosixPath('data/put')].
```

**Comment by 0xv0idx** [comment]
dont give a file directly use
python -m vall_e.emb.qnt data/put
python -m vall_e.emb.g2p data/put
