### ISSUE TITLE
Error on MacOS Ventura

### ISSUE THREAD

**Issue by LiveRock** [enhuiz/vall-e#70]
Hi

I am using MacBook Pro M1 Pro.
I have recorded a short audio file in wav and put it in the data/peter folder
I get the following errors when trying to train:

**python -m vall_e.emb.qnt data/peter** 

```
Traceback (most recent call last):
  File "/python3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/vall-e/vall-e/vall_e/emb/qnt.py", line 6, in <module>
    import soundfile
ModuleNotFoundError: No module named 'soundfile'
```

What did I do wrong?

**Comment by leslie0912** [comment]
me too

**Comment by KodeurKubik** [comment]
You can just do `pip install soundfile` I guess

**Comment by LiveRock** [comment]
done the following:

```
pip install soundfile
pip install torch 
pip install torchaudio
pip install einops
pip install encodec
pip install tqdm 
pip install diskcache 
pip install omegaconf 
```

I still get the errors:

```
Traceback (most recent call last):
  File "/python3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/python3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Volumes/EVO980PRO2TB/Projects/speech/vall-e/vall-e/vall_e/emb/qnt.py", line 15, in <module>
    from ..config import cfg
  File "/Volumes/EVO980PRO2TB/Projects/speech/vall-e/vall-e/vall_e/config.py", line 7, in <module>
    from .utils import Config as ConfigBase
  File "/Volumes/EVO980PRO2TB/Projects/speech/vall-e/vall-e/vall_e/utils/__init__.py", line 1, in <module>
    from .config import Config
  File "/Volumes/EVO980PRO2TB/Projects/speech/vall-e/vall-e/vall_e/utils/config.py", line 13, in <module>
    class Config:
  File "/Volumes/EVO980PRO2TB/Projects/speech/vall-e/vall-e/vall_e/utils/config.py", line 21, in Config
    max_grad_norm: float | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Comment by KodeurKubik** [comment]
Use python3.10 and pip3.10
You are currently using a python version that is not supported by this code.
