### ISSUE TITLE
Unsupported gpu architecture 'compute_89'

### ISSUE THREAD

**Issue by utiq** [enhuiz/vall-e#71]
I have an RTX 4090. I'm not sure if that's the problem

```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/TH -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/cesar/.conda/envs/valle/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -std=c++17 -c /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o
FAILED: multi_tensor_adam.cuda.o
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/TH -isystem /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/cesar/.conda/envs/valle/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -std=c++17 -c /home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_89'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cesar/.conda/envs/valle/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cesar/.conda/envs/valle/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 128, in <module>
    main()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 119, in main
    trainer.train(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/utils/trainer.py", line 125, in train
    engines = engines_loader()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/utils/engines.py", line 22, in __init__
    super().__init__(None, *args, **kwargs)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1360, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 73, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
```

**Comment by utiq** [comment]
Never mind, it was the Cuda version that it was not updated for the GPU. Version 11.8 is required.
