### ISSUE TITLE
Checkpoint error

### ISSUE THREAD

**Issue by utiq** [enhuiz/vall-e#75]
I get this error when the checkpoint is created

```
[2023-03-22 21:58:46,352] [INFO] [logging.py:93:log_dist] [Rank 0] Saving model checkpoint: ckpts/libri/ar/model/default/mp_rank_00_model_states.pt
[2023-03-22 21:58:46,352] [INFO] [torch_checkpoint_engine.py:17:save] [Torch] Saving ckpts/libri/ar/model/default/mp_rank_00_model_states.pt...
[2023-03-22 21:58:49,004] [INFO] [torch_checkpoint_engine.py:19:save] [Torch] Saved ckpts/libri/ar/model/default/mp_rank_00_model_states.pt.
[2023-03-22 21:58:49,004] [INFO] [torch_checkpoint_engine.py:29:commit] [Torch] Checkpoint default is ready now!
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [02:10<00:00,  2.29it/s]100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [02:13<00:00, 133.48s/it]2023-03-22 22:01:02 - __main__ - INFO - GR=0;LR=0 -
Eval: {'global_step': 50000, 'name': 'subtrain'}.
2023-03-22 22:01:02 - __main__ - INFO - GR=0;LR=0 -
{"global_step": 50000, "name": "subtrain"}.
  0%|                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/cesar/.conda/envs/valle/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cesar/.conda/envs/valle/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 128, in <module>
    main()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 119, in main
    trainer.train(
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/utils/trainer.py", line 205, in train
    eval_fn(engines=engines)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/utils/distributed.py", line 69, in wrapped
    return fn(*args, **kwargs)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 117, in eval_fn
    run_eval(engines, "val", val_dl)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/train.py", line 70, in run_eval
    for batch in tqdm(dl):
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cesar/.conda/envs/valle/lib/python3.10/site-packages/vall_e/data.py", line 165, in __getitem__
    text = torch.tensor([*map(self.phone_symmap.get, _get_phones(path))])
RuntimeError: Could not infer dtype of NoneType
```

**Comment by AstralScribe** [comment]
I am also getting the same error. Were you able to resolve this error?

**Comment by chenyi0818** [comment]
+1

**Comment by BruceXiangnanREN** [comment]
Same here, did you solve it?
