### ISSUE TITLE
MemoryError: std::bad_alloc on multiple platforms

### ISSUE THREAD

**Issue by masoncfrancis** [enhuiz/vall-e#77]
I am trying to train with a recording and transcript of a speech. I have follow the instructions to a t. 

Every time I run `python3.10 -m vall_e.emb.qnt ./trainingData` I get the following error:

```
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/masoncfrancis/donaldVoice/venv/lib/python3.10/site-packages/vall_e/emb/qnt.py", line 95, in <module>
    main()
  File "/home/masoncfrancis/donaldVoice/venv/lib/python3.10/site-packages/vall_e/emb/qnt.py", line 90, in main
    qnt = encode_from_file(path)
  File "/home/masoncfrancis/donaldVoice/venv/lib/python3.10/site-packages/vall_e/emb/qnt.py", line 71, in encode_from_file
    wav, sr = torchaudio.load(str(path))
  File "/home/masoncfrancis/donaldVoice/venv/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 251, in load
    ret = torch.ops.torchaudio.sox_io_load_audio_file(
  File "/home/masoncfrancis/donaldVoice/venv/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
MemoryError: std::bad_alloc
```

I have tried on Windows, WSL, Ubuntu, and Debian, all with the same issue. I have even tried different versions of PyTorch, some w/ CUDA support and some without. I always run into this issue.

**Comment by Mataleviatanes** [comment]
Hola
