### ISSUE TITLE
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)

### ISSUE THREAD

**Issue by tuannvhust** [enhuiz/vall-e#78]
I got this bug when I run trainning command:
`python -m vall_e.train yaml=config/your_data/ar.yml`
Thu bug is:
```
12807it [00:00, 58951.20it/s]
2023-03-27 04:28:19 - vall_e.data - INFO - GR=0;LR=0 - 
{'</s>': 1, '<s>': 2, 'AA0': 3, 'AA1': 4, 'AA2': 5, 'AE1': 6, 'AH0': 7, 'AH1': 8, 'AO0': 9, 'AO1': 10, 'AO2': 11, 'AW1': 12, 'AW2': 13, 'AY1': 14, 'B': 15, 'CH': 16, 'D': 17, 'DH': 18, 'EH1': 19, 'EH2': 20, 'ER0': 21, 'EY1': 22, 'EY2': 23, 'F': 24, 'G': 25, 'HH': 26, 'IH0': 27, 'IH1': 28, 'IY0': 29, 'IY1': 30, 'IY2': 31, 'JH': 32, 'K': 33, 'L': 34, 'M': 35, 'N': 36, 'NG': 37, 'OW0': 38, 'OW1': 39, 'OY0': 40, 'OY1': 41, 'P': 42, 'R': 43, 'S': 44, 'SH': 45, 'T': 46, 'TH': 47, 'UW0': 48, 'UW1': 49, 'UW2': 50, 'V': 51, 'W': 52, 'Y': 53, 'Z': 54, 'ZH': 55, '_': 56}
2023-03-27 04:28:19 - vall_e.data - INFO - GR=0;LR=0 - 
{'your_data': 0}
2023-03-27 04:28:19 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (train): 6866.
2023-03-27 04:28:19 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (val): 20.
[2023-03-27 04:28:19,896] [INFO] [comm.py:654:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
2023-03-27 04:28:19 - torch.distributed.distributed_c10d - INFO - GR=0;LR=0 - 
Added key: store_based_barrier_key:1 to store for rank: 0
2023-03-27 04:28:19 - torch.distributed.distributed_c10d - INFO - GR=0;LR=0 - 
Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
2023-03-27 04:28:21 - torch.distributed.distributed_c10d - INFO - GR=0;LR=0 - 
Added key: store_based_barrier_key:2 to store for rank: 0
2023-03-27 04:28:21 - torch.distributed.distributed_c10d - INFO - GR=0;LR=0 - 
Rank 0: Completed store-based barrier for key:store_based_barrier_key:2 with 1 nodes.
[2023-03-27 04:28:21,783] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vall-e/vall_e/train.py", line 128, in <module>
    main()
  File "/workspace/vall-e/vall_e/train.py", line 119, in main
    trainer.train(
  File "/workspace/vall-e/vall_e/utils/trainer.py", line 125, in train
    engines = engines_loader()
  File "/workspace/vall-e/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/workspace/vall-e/vall_e/utils/engines.py", line 24, in __init__
    super().__init__(None, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 330, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1195, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1272, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/usr/local/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 460, in load
    return self.jit_load(verbose)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 475, in jit_load
    assert_no_cuda_mismatch()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 89, in assert_no_cuda_mismatch
    cuda_major, cuda_minor = installed_cuda_version()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 41, in installed_cuda_version
    assert cuda_home is not None, "CUDA_HOME does not exist, unable to compile CUDA op(s)"
AssertionError: CUDA_HOME does not exist, unable to compile CUDA op(s)
```
How should I fix this bug? Pls help

**Comment by zolero** [comment]
Please just google this... It says that the system CUDA_HOME environment variable does not exist. Which means you either have not installed CUDA or have not configured it correctly. This is not related to this Github repo and is not a bug. It is your system that is not installed correctly.

**Comment by LanShanPi** [comment]
Have you solved this problem yet.

**Comment by tuannvhust** [comment]
@LanShanPi nopee, I gave up
