### ISSUE TITLE
ImportError: cannot import name 'Config' from 'vall_e.utils' (unknown location)

### ISSUE THREAD

**Issue by tcmartin** [enhuiz/vall-e#80]
code to reproduce
```
#%cd vall-e
!python -m vall_e.emb.qnt data/libri
!python -m vall_e.emb.g2p data/libri

```
Output
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/emb/qnt.py", line 15, in <module>
    from ..config import cfg
  File "/content/vall-e/vall_e/config.py", line 7, in <module>
    from .utils import Config as ConfigBase
ImportError: cannot import name 'Config' from 'vall_e.utils' (unknown location)

**Comment by guii** [comment]
you are missing utils.
clone the git again with  --recurse-submodules option like this:
 git clone --recurse-submodules https://github.com/enhuiz/vall-e.git
