### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by 0913ktg** [enhuiz/vall-e#82]
Hi, I ran vall-e/train to train vall-e using the Korean dataset.
Created file 'qnt.pt ' and file 'normalized.txt' in python 3.10 environment.
The development environment has been established using the docker container.
Certain data can be learned, but using data from multiple speakers results in the following error.
It went well when I learned using data from two speakers to see if there was a problem with the multispers related part.
If anyone has experienced a related problem, please help. 
Thank you.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/vall-e/vall_e/train.py", line 131, in <module>
    main()
  File "/data/vall-e/vall_e/train.py", line 122, in main
    trainer.train(
  File "/data/vall-e/vall_e/utils/trainer.py", line 157, in train
    stats = engines.step(feeder=train_feeder, batch=batch)
  File "/data/vall-e/vall_e/utils/engines.py", line 172, in step
    raise e
  File "/data/vall-e/vall_e/utils/engines.py", line 134, in step
    maybe_loss_and_engine_stats = feeder(
  File "/data/vall-e/vall_e/train.py", line 41, in train_feeder
    _ = model(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1832, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/vall-e/vall_e/vall_e/ar.py", line 49, in forward
    return super().forward(
  File "/data/vall-e/vall_e/vall_e/base.py", line 433, in forward
    self.proms_emb(proms_list),
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/vall-e/vall_e/vall_e/base.py", line 266, in forward
    xi = F.one_hot(xi, num_classes=self.n_tokens)  # t l' k
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by 0913ktg** [comment]
I am currently using the pytorch 1.12.1 version. Could it be a problem if I didn't use the pytorch 1.13.1 version?

**Comment by 0913ktg** [comment]
It was a problem caused by the difference in the number of tokens in Korean and English. It is solved by making the embedding layer dimension larger than the number of Korean tokens.
