### ISSUE TITLE
Colab doesn't work.

### ISSUE THREAD

**Issue by HyperionSniper** [enhuiz/vall-e#85]
When I run the Colab linked in this GitHub's README, training the model fails with this:
AttributeError: 'NoneType' object has no attribute 'optimizer_name'

It seems to have something to do with the config. Also of note, I tried debugging the config using `python -m vall_e.utils.config yaml=config/test/ar.yml`, but that doesn't work either, although I haven't looked too deeply into it so I don't know if that's how you're supposed to use it.

I managed to get it working by doing something with --force-reinstall deepspeed==0.8.0 and then reinstalling the VALL-E module from git, but I don't know exactly what I did to get it working, and I can't reproduce it.

```
[2023-04-14 16:40:26,592] [INFO] [comm.py:586:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/export.py", line 25, in <module>
    main()
  File "/content/vall-e/vall_e/export.py", line 14, in main
    engine = load_engines()
  File "/content/vall-e/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/content/vall-e/vall_e/utils/engines.py", line 22, in __init__
    super().__init__(None, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 264, in __init__
    self._do_sanity_check()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 988, in _do_sanity_check
    if self.optimizer_name() is not None:
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 648, in optimizer_name
    return (self.client_optimizer.__class__.__name__ if self.client_optimizer else self._config.optimizer_name)
AttributeError: 'NoneType' object has no attribute 'optimizer_name'
[2023-04-14 16:40:29,592] [INFO] [comm.py:586:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/export.py", line 25, in <module>
    main()
  File "/content/vall-e/vall_e/export.py", line 14, in main
    engine = load_engines()
  File "/content/vall-e/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/content/vall-e/vall_e/utils/engines.py", line 22, in __init__
    super().__init__(None, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 264, in __init__
    self._do_sanity_check()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 988, in _do_sanity_check
    if self.optimizer_name() is not None:
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 648, in optimizer_name
    return (self.client_optimizer.__class__.__name__ if self.client_optimizer else self._config.optimizer_name)
AttributeError: 'NoneType' object has no attribute 'optimizer_name'
```

**Comment by HyperionSniper** [comment]
I got it to work by changing the dependencies in setup.py to == instead of >=.

**Comment by samuelsogbesan** [comment]
Which dependencies @HyperionSniper? All of them?

**Comment by HyperionSniper** [comment]
I changed packages I thought might be important. I might have based it on
some errors I saw, but I don't remember anymore. 'torch' is probably an
important one. Anyway, here's my version:
        "coloredlogs==15.0.1",
        "deepspeed==0.7.7",
        "diskcache==5.4.0",
        "einops==0.6.0",
        "encodec==0.1.1",
        "g2p_en==2.1.0",
        "humanize==4.4.0",
        "matplotlib==3.6.0",
        "numpy>=1.23.3",
        "omegaconf==2.2.3",
        "openTSNE==0.6.2",
        "pandas>=1.5.0",
        "soundfile==0.11.0",
        "torch==1.13.0",
        "torchaudio==0.13.0",
        "tqdm==4.64.1",
