### ISSUE TITLE
 run vall-e in colab ,!python -m vall_e.train yaml=config/test/ar.yml why the test file can not run .

### ISSUE THREAD

**Issue by samual30000** [enhuiz/vall-e#96]
/content/vall-e
2it [00:00, 6034.97it/s]
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
2023-05-02 10:13:56 - vall_e.data - INFO - GR=0;LR=0 - 
{'</s>': 1, '<s>': 2, 'AH0': 3, 'D': 4, 'ER1': 5, 'HH': 6, 'L': 7, 'OW1': 8, 'W': 9, '_': 10}
2023-05-02 10:13:56 - vall_e.data - INFO - GR=0;LR=0 - 
{'test': 0}
2023-05-02 10:13:56 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (train): 2.
2023-05-02 10:13:56 - vall_e.data - INFO - GR=0;LR=0 - 
#samples (val): 0.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/train.py", line 128, in <module>
    main()
  File "/content/vall-e/vall_e/train.py", line 119, in main
    trainer.train(
  File "/content/vall-e/vall_e/utils/trainer.py", line 125, in train
    engines = engines_loader()
  File "/content/vall-e/vall_e/train.py", line 21, in load_engines
    model=trainer.Engine(
  File "/content/vall-e/vall_e/utils/engines.py", line 22, in __init__
    super().__init__(None, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 244, in __init__
    self._do_sanity_check()
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 968, in _do_sanity_check
    if self.optimizer_name() is not None:
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 628, in optimizer_name
    return (self.client_optimizer.__class__.__name__ if self.client_optimizer else self._config.optimizer_name)
AttributeError: 'NoneType' object has no attribute 'optimizer_name'

**Comment by samual30000** [comment]
AttributeError: 'NoneType' object has no attribute 'optimizer_name'   why the test file can not run .

**Comment by samual30000** [comment]
!pip install deepspeed==0.8.3 make it alright

**Comment by samual30000** [comment]
cloese
