### ISSUE TITLE
Issue when synthesising

### ISSUE THREAD

**Issue by MisiBuku** [enhuiz/vall-e#99]
When I try to run synthesis test:
`!python -m vall_e "BUT WOULD MAKE THE VERY BEST OF THE CHANCES THAT LIFE OFFERED HER AND CONQUER CIRCUMSTANCES BY HER EXCEPTIONAL CLEVERNESS" /content/data/libri/248-130644-0018.wav toy1.wav`

I get:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/vall-e/vall_e/__main__.py", line 43, in <module>
    main()
  File "/content/vall-e/vall_e/__main__.py", line 29, in main
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
  File "/content/vall-e/vall_e/__main__.py", line 29, in <listcomp>
    phns = torch.tensor([symmap[p] for p in g2p.encode(args.text)])
KeyError: 'B'`

What I use:

- I'm running my code on collab, because I don't have my own GPU.

- Training only worked when i used nar, so that's what I've trained with

- deepspeed 0.8.3 version.

Maybe someone knows something? Or could help me make it work? I need this for university project..🙏🙏🙏

**Comment by SoumiK-777** [comment]
Same issue, the model doesn't synthesize anything other than 'hello world'. When I try to synthesize hello world it outputs only noise

**Comment by vidigal** [comment]
Same issue here :(

**Comment by Abdulk084** [comment]
same here
